[package]
name = "fourre-tout"
version = "1.0.0"
authors = ["Mickaël Leduque <mleduque@gmail.com>"]
edition = "2018"

[dependencies]
chrono = "0.4.6"
diesel = { version = "1.4.1", features = ["postgres"] }
dotenv = "0.13.0"
serde = { version = "1.0.87", features = ["derive"] }
serde_json = "1.0.38"