[package]
name = "fourre-tout"
version = "1.0.0"
authors = ["Mickaël Leduque <mleduque@gmail.com>"]
edition = "2018"

[dependencies]
diesel = { version = "1.4.1", features = ["postgres"] }
dotenv = "0.13.0"
